services:
  italy-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: italy-ui
    hostname: italy-ui
    restart: always
    environment:
      - VITE_API_URL_PROD=${VITE_API_URL_PROD}
      - VITE_APP_PORT=${VITE_APP_PORT}
